# -*- coding: utf-8 -*-
"""motioncut_exp3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Ii6w9kCXq-A9zC0fjudS9wm4huyv-N0
"""

class Expense:
    def __init__(self, amount, description, category):
        self.amount = amount
        self.description = description
        self.category = category

class ExpenseTracker:
    def __init__(self):
        self.expenses = []

    def add_expense(self, expense):
        self.expenses.append(expense)

    def get_monthly_summary(self, month, year):
        # Logic to calculate and return monthly summary
        pass

    def get_category_summary(self, category):
        # Logic to calculate and return category-wise expenditure
        pass

# User Interface (using a simple command-line interface for demonstration)
def main():
    tracker = ExpenseTracker()
    while True:
        print("1. Add Expense")
        print("2. View Monthly Summary")
        print("3. View Category-wise Expenditure")
        print("4. Exit")
        choice = input("Enter your choice: ")
        if choice == "1":
            amount = float(input("Enter the amount spent: "))
            description = input("Enter a brief description: ")
            category = input("Enter the category: ")
            expense = Expense(amount, description, category)
            tracker.add_expense(expense)
        elif choice == "2":
            month = input("Enter the month: ")
            year = input("Enter the year: ")
            print(tracker.get_monthly_summary(month, year))
        elif choice == "3":
            category = input("Enter the category: ")
            print(tracker.get_category_summary(category))
        elif choice == "4":
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()