# -*- coding: utf-8 -*-
"""motioncut_exp4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KlzliFiifDc9DG5mQej_AULJLRW2JxXg
"""

import random
import string

def generate_password(length=12):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def generate_multiple_passwords(num_passwords, length=12):
    passwords = [generate_password(length) for _ in range(num_passwords)]
    return passwords

if __name__ == "__main__":
    num_passwords = int(input("Enter the number of passwords to generate: "))
    length = int(input("Enter the length of each password: "))

    generated_passwords = generate_multiple_passwords(num_passwords, length)

    print("\nGenerated Passwords:")
    for password in generated_passwords:
        print(password)