# -*- coding: utf-8 -*-
"""motioncut_exp1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YCAZgTkroNjSzOk2K3kYnQPeyYT4d50F
"""

class Quiz:
    def __init__(self, questions, options, answers):
        self.questions = questions
        self.options = options
        self.answers = answers
        self.score = 0

    def display_question(self, question_num):
        print(self.questions[question_num])
        for option in self.options[question_num]:
            print(option)
        user_answer = input("Your answer: ")
        self.check_answer(question_num, user_answer)

    def check_answer(self, question_num, user_answer):
        if user_answer.lower() == self.answers[question_num]:
            print("Correct!")
            self.score += 1
        else:
            print("Incorrect. The correct answer is: " + self.answers[question_num])

    def display_final_score(self):
        print("Your final score is: " + str(self.score) + "/" + str(len(self.questions)))

# Define the quiz content
questions = [
    "What is the name of my dog?",
    "What is the largest planet in our solar system?",
    "What is my name?"
]

options = [
    ["A) Brownie", "B) Lexi", "C) Baby"],
    ["A) Jupiter", "B) Saturn", "C) Mars"],
    ["A) Charles", "B) Abhishek", "C) John"]
]

answers = ["b", "a", "b"]

# Create an instance of the Quiz class
my_quiz = Quiz(questions, options, answers)

# Run the quiz
for i in range(len(questions)):
    my_quiz.display_question(i)

my_quiz.display_final_score()